src/AppBundle/Entity/Agent.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Agent
 *
 * @ORM\Table(name="agent")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AgentRepository")
 */
class Agent extends User {

    public function __construct() {
        parent::__construct();
        $this->agentregions = new ArrayCollection();
        $this->laboratoryagents = new ArrayCollection();
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean", nullable=true)
     */
    private $perfumery;

    /**
     * @ORM\OneToMany(targetEntity="AgentRegion", mappedBy="agent", cascade={"all"}, orphanRemoval=true)
     */
    private $agentregions;

    /**
     * @ORM\OneToMany(targetEntity="LaboratoryAgent", mappedBy="agent", cascade={"all"}, orphanRemoval=true)
     */
    private $laboratoryagents;

    public function getDiscr(){
        return "agent";
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    public function addAgentRegion(AgentRegion $agentRegion) {
        $agentRegion->setAgent($this);

        $this->agentregions->add($agentRegion);
    }

    public function removeAgentRegion(AgentRegion $agentRegion) {
        $this->agentregions->removeElement($agentRegion);
    }

    /**
     *
     * @return type
     */
    public function getAgentregions() {
        return $this->agentregions;
    }

    /**
     *
     */
    public function setAgentregions($agentregions) {
        $this->agentregions = $agentregions;
    }

    public function setLaboratoryagents($laboratoryagents) {
        $this->laboratoryagents = $laboratoryagents;
        return $this;
    }

    /**
     * @return type
     */
    public function getLaboratoryagents() {
        return $this->laboratoryagents;
    }

    /**
     *
     * @return type
     */
    public function getPerfumery() {
        return $this->perfumery;
    }

    /**
     *
     */
    public function setPerfumery($perfumery) {
        $this->perfumery = $perfumery;
    }

}

src/AppBundle/Controller/Backend/AffiliatedController.php
<?php

namespace AppBundle\Controller\Backend;

use AppBundle\Controller\BaseController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Affiliated;
use AppBundle\Entity\AffiliatedLaboratory;
use AppBundle\Form\AffiliatedType;

/**
 * Affiliated controller.
 *
 * @Route("/backend/affiliated")
 */
class AffiliatedController extends BaseController
{
    /**
     * @Route("/" , name="backend_affiliated")
     * @Template("AppBundle:Backend\Affiliated:index.html.twig")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository("AppBundle:Affiliated")->findAll();

        return array(
            'entities' => $entities,
        );
    }

    /**
     * Displays a form to create a new Affiliated entity.
     *
     * @Route("/new/", name="backend_affiliated_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {

      $em = $this->getDoctrine()->getManager();


        $entity = new Affiliated();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a new Affiliated entity.
     *
     * @Route("/create/", name="backend_affiliated_create")
     * @Method("POST")
     * @Template("AppBundle:Backend\Affiliated:new.html.twig")
     */
    public function createAction(Request $request)
    {

      $em = $this->getDoctrine()->getManager();
      $affiliatedlaboratory = new AffiliatedLaboratory();

     
        $entity = new Affiliated();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);
        if ($form->isValid()) {
          if($this->validUsernameEmail($entity)){
            try{

              $email = $form->get('email')->getData();

              // Set entity fields custom
              $this->requestCustomForm($request, $entity);

              $entity->setUsername($email);
              $entity->setEnabled(true);
              $entity->setRoles(array("ROLE_USER"));

              $em->persist($entity);
              $em->flush();

              $laboratory = $em->getRepository("AppBundle:Laboratory")->findOneById(1);

              $affiliatedlaboratory->setAffiliated($entity);
              $affiliatedlaboratory->setLaboratory($laboratory);
              $em->persist($affiliatedlaboratory);
              $em->flush();

              $request->getSession()
                   ->getFlashBag()
                   ->add('success', 'Registro criado com sucesso!');
              if($this->getUser() == null){
                $this->sendEmail('Bem vindo ao sistema de lanches',$email,'
        Caro(a), '.$entity->getFirstName().'!<br>
        Aproveite os nossos lanches!<br><br>
        

');
                return $this->redirect($this->generateUrl('fos_user_security_login'));
              }else{
               return $this->redirect($this->generateUrl('backend_affiliated'));
              }
            }catch(\Exception $e)
            {
              $this->log($e);
                $request->getSession()
                ->getFlashBag()
                ->add('error', 'Ocorreu algum erro inesperado. Tente novamente mais tarde!');
            }
          }else{
            $request->getSession()
                ->getFlashBag()
                ->add('error', 'Email já cadastrado, tente novamente!');
          }
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Affiliated entity.
     *
     * @param Affiliated $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Affiliated $entity)
    {
        $form = $this->createForm(new AffiliatedType(), $entity, array(
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to edit an existing Affiliated entity.
     *
     * @Route("/{id}/edit", name="backend_affiliated_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
      if ($this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN')) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Affiliated')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Affiliated entity.');
        }

        $editForm = $this->createEditForm($entity);
        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
        );
      }else{
        throw $this->createNotFoundException('Você não tem permissão para acessar esta tela.');
      }
    }

    /**
    * Creates a form to edit a Affiliated entity.
    *
    * @param Affiliated $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Affiliated $entity)
    {
        $form = $this->createForm(new AffiliatedType(), $entity);

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Affiliated entity.
     *
     * @Route("/{id}/update", name="backend_affiliated_update")
     * @Template("AppBundle:Backend\Affiliated:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
      if ($this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN')) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Affiliated')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Affiliated entity.');
        }

        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
          if($this->validUsernameEmail($entity)){
            try{
              // Set entity fields custom
              $this->requestCustomForm($request, $entity);

              $em->flush();

              $request->getSession()
                   ->getFlashBag()
                   ->add('success', 'Registro atualizado com sucesso!');

              return $this->redirect($this->generateUrl('backend_affiliated'));
            }catch(\Exception $e){
                $this->log($e);
                $request->getSession()
                ->getFlashBag()
                ->add('error', 'Ocorreu algum erro inesperado. Tente novamente mais tarde!');
            }
          }else{
            $request->getSession()
                    ->getFlashBag()
                    ->add('error', 'Email já cadastrado, tente novamente!');
          }
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
        );
      }else{
        throw $this->createNotFoundException('Você não tem permissão para acessar esta tela.');
      }
    }
    /**
     * Deletes a Affiliated entity.
     *
     * @Route("/{id}/delete", name="backend_affiliated_delete")
     *
     */
    public function deleteAction(Request $request, $id)
    {
      if ($this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN')) {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('AppBundle:Affiliated')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Affiliated entity.');
        }

        $em->remove($entity);
        $em->flush();

        $request->getSession()
             ->getFlashBag()
             ->add('success', 'Registro excluído com sucesso!');

        return $this->redirect($this->generateUrl('backend_affiliated'));
      }else{
        throw $this->createNotFoundException('Você não tem permissão para acessar esta tela.');
      }
    }

     /**
     * Atualiza o Status do Usuários para ATIVO
     *
     * @Route("/?id={id}", name="backend_affiliated_status")
     */
    public function activateStatusAction($id)
    {
      if ($this->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN')) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Affiliated')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Affiliated entity.');
        }

        $condicao = $entity->getStatus();
        if($condicao == "Ativo")
           $entity->setEnabled(false);
        else
            $entity->setEnabled(true);

        $em->persist($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('backend_affiliated'));
      }else{
        throw $this->createNotFoundException('Você não tem permissão para acessar esta tela.');
      }
    }

    /**
     * Set entity fields custom
     * @param Request $request
     * @param Entity $entity
     */
    public function requestCustomForm($request, $entity)
    {
        $em = $this->getDoctrine()->getManager();
        $affiliatedCustomArray = $request->request->get('affiliated_custom');

        if (!empty($affiliatedCustomArray['plainPassword'])) {
            $encoder = $this->container->get('security.encoder_factory')->getEncoder($entity);
            $new_pwd_encoded = $encoder->encodePassword($affiliatedCustomArray['plainPassword'], $entity->getSalt());
            $entity->setPassword($new_pwd_encoded);
        }
    }

private function sendEmail($titulo, $email, $message){
      $mailMessage = \Swift_Message::newInstance()
              ->setSubject($titulo)

src/AppBundle/Controller/Backend/CotacoesController.php
<?php

namespace AppBundle\Controller\Backend;

use AppBundle\Controller\BaseController;
use AppBundle\Entity\Cotacoes;
use AppBundle\Form\CotacoesType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

/**
 * Cotacoes controller.
 *
 * @Route("backend/cotacoes")
 */
class CotacoesController extends BaseController
{

    /**
     * Lists all distributors entities.
     *
     * @Route("/", name="backend_cotacoes_index")
     * @Method("GET")
     * @Template("AppBundle:Backend\Cotacoes:index.html.twig")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $cotacoes = $em->getRepository('AppBundle:Cotacoes')->findByUser($this->getUser());
        return array(
            'cotacoes' => $cotacoes,
        );
    }

    /**
     * Lists all distributors entities.
     *
     * @Route("/representante", name="backend_cotacoes_representante_index")
     * @Method("GET")
     * @Template("AppBundle:Backend\Cotacoes:index.html.twig")
     */
    public function indexRepresentanteAction()
    {
        $em = $this->getDoctrine()->getManager();
        $verify = '';
        $agent = $em->getRepository('AppBundle:Agent')->find($this->getUser());
        if($agent != null){
            if($agent->getPerfumery() == 1){
                $verify = 'perfumery';
            }
        }
        if($verify != null){
            $cotacoes = $em->getRepository('AppBundle:Cotacoes')->findAll();
        }else{
            $cotacoes = $em->getRepository('AppBundle:Cotacoes')->findByUser($this->getUser());
        }
        return array(
            'cotacoes' => $cotacoes,
        );
    }

    /**
     * Creates a new cotacoes entity.
     *
     * @Route("/new", name="backend_cotacoes_new")
     * @Method({"GET", "POST"})
     * @Template("AppBundle:Backend\Cotacoes:new.html.twig")
     */
    public function newAction(Request $request)
    {
        $cotacoes = new Cotacoes();
        $form         = $this->createForm('AppBundle\Form\CotacoesType', $cotacoes);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $cotacoes->setUser($this->getUser());
            $em->persist($cotacoes);
            $em->flush($cotacoes);

            $request->getSession()
                ->getFlashBag()
                ->add('success', 'Registro criado com sucesso!');

            return $this->redirectToRoute('backend_cotacoes_index');
        }

        return array(
            'cotacoes' => $cotacoes,
            'form'         => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing cotacoes entity.
     *
     * @Route("/{id}/edit", name="backend_cotacoes_edit")
     * @Method({"GET", "POST"})
     * @Template("AppBundle:Backend\Cotacoes:edit.html.twig")
     */
    public function editAction(Request $request, Cotacoes $cotacoes)
    {
        $editForm = $this->createForm('AppBundle\Form\CotacoesType', $cotacoes);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $request->getSession()
                ->getFlashBag()
                ->add('success', 'Registro atualizado com sucesso!');

            return $this->redirectToRoute('backend_cotacoes_edit', array('id' => $cotacoes->getId()));
        }

        return array(
            'cotacoes' => $cotacoes,
            'edit_form'    => $editForm->createView(),
        );
    }

    /**
     * Deletes a cotacoes entity.
     *
     * @Route("/{id}/delete", name="backend_cotacoes_delete")
     */
    public function deleteAction(Request $request, Cotacoes $cotacoes)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($cotacoes);
        $em->flush($cotacoes);

        $request->getSession()
            ->getFlashBag()
            ->add('success', 'Registro excluído com sucesso!');

        return $this->redirectToRoute('backend_cotacoes_index');
    }

}

src/AppBundle/Controller/Backend/HomeController.php
<?php

namespace AppBundle\Controller\Backend;

use AppBundle\Controller\BaseController;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class HomeController extends BaseController
{
    /**
     * @Route("/backend", name= "backend_home")
     * @Template()
     */
    public function indexAction(Request $request)
    {
       if($this->getUser() == null){
       return $this->redirect($this->generateUrl('fos_user_security_login'));
       }
    }

}

src/AppBundle/Controller/Backend/RequestController.php
<?php

namespace AppBundle\Controller\Backend;

use AppBundle\Controller\BaseController;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class RequestController extends BaseController
{
    /**
     * @Route("/requests", name= "requests_show")
     * @Template("AppBundle:Backend\Requests:index.html.twig")
     */
    public function indexAction(Request $request){
    	
    }

}

src/AppBundle/Resources/views/Backend/Cotacoes/edit.html.twig
{% extends '::Backend/base.html.twig' %}

{% block body -%}
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Editar</h1>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Editar Cotação</h3>
                        </div><!-- /.box-header -->
                        <section class="content-header">
                            <ol class="breadcrumb">
                                <li><a href="{{ path('backend_cotacoes_index') }}"><i class="fa fa-dashboard"></i> Cotações</a></li>
                                <li class="active">Editar</li>
                            </ol>
                        </section>
                        <div class="box-body table-responsive no-padding">

                            <form class="" action="{{ path('backend_cotacoes_edit',{'id': cotacoes.id}) }}" method="post" {{ form_enctype(edit_form) }}>
                                {{ form_widget(edit_form._token) }}

                                {% block messages %}
                                    {{ parent() }}
                                    {{ form_errors(edit_form) }}
                                {% endblock %}

                                {% include 'AppBundle:Backend/Cotacoes:form.html.twig' with {'form': edit_form} %}

                                <div class="box-footer">
                                    {% if app.user.discr != 'agent' %}
                                        <button type="submit" class="btn btn-success">Editar</button>
                                    {% endif %}
                                    <a href="{{ path('backend_cotacoes_index') }}" class="btn btn-default">Voltar</a>
                                </div>

                            </form>

                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts filter='?uglifyjs2'
        '@AppBundle/Resources/public/js/custom/Agent/form.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

src/AppBundle/Resources/views/Backend/Cotacoes/form.html.twig
{{ form_widget(form.archive) }}
<div class="box-body">
    <div class="form-group">
        {{ form_errors(form.name) }}
        <label for="cotacoes_name">Nome</label>
        {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="row">
        {% if app.user.discr != 'agent' %}
            <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                {{ form_errors(form.archiveTemp) }}
                <label for="cotacoes_archiveTemp">Arquivo(<b>XLS</b>)</label>
                {{ form_widget(form.archiveTemp, {'attr': {'class': 'form-control'}}) }}
            </div>
        {% endif %}
        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
            {% if cotacoes.archive != null %}
                <a href='http://localhost:8000/uploads/perfumaria/cotacoes/{{ cotacoes.archive }}' class='btn btn-success'>Visualizar</a>
            {% endif %}
        </div>
    </div>
</div><!-- /.box-body -->

src/AppBundle/Resources/views/Backend/Cotacoes/index.html.twig
{% extends '::Backend/base.html.twig' %}

{% block body -%}
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Cotações</h1>
        </section>

        <!-- Main content -->
        <section class="content">
            {% if app.user.discr != 'agent' %}
            <div class="row ">
                <div class="col-xs-12 bs-50">
                    <a href="{{ path('backend_cotacoes_new') }}" class="btn btn-success">Novo</a>
                </div>
            </div>
            {% endif %}
            <br>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-tile">
                        <div class="panel-body pn pl20 p5">
                            <div class="col-sm-6 col-md-4">
                                <h2 class="mt15 lh15">
                                    <span class="counter"><b class="ng-binding">{{cotacoes|length}}</b></span>
                                    <span class="text-muted custom-h2"> Cotações</span></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Listagem de Cotações</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for entity in cotacoes %}
                                        <tr>
                                            <td>{{ entity.name }}</td>
                                            <td>
                                                <a href="{{ path('backend_cotacoes_edit', { 'id': entity.id }) }}" class="btn btn-primary">Editar</a>
                                                {% if app.user.discr != 'agent' %}
                                                    <a href="javascript:void(0);" data-url="{{ path('backend_cotacoes_delete', { 'id': entity.id }) }}" class="btn btn-danger delete_item">Excluir</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
            </div>
        </section><!-- /.content -->
    </aside><!-- /.right-side -->
{% endblock %}

src/AppBundle/Resources/views/Backend/Cotacoes/new.html.twig
{% extends '::Backend/base.html.twig' %}

{% block body -%}
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Cadastrar</h1>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Cadastrar Cotação</h3>
                </div><!-- /.box-header -->
                <section class="content-header">
                    <ol class="breadcrumb">
                        <li><a href="{{ path('backend_cotacoes_index') }}"><i class="fa fa-dashboard"></i> Cotações</a></li>
                        <li class="active">Cadastrar</li>
                    </ol>
                </section>
                <div class="box-body table-responsive no-padding">

                        <form class="" action="{{ path('backend_cotacoes_new') }}" method="post" {{ form_enctype(form) }}>

                            {{ form_widget(form._token) }}

                            {% block messages %}
                                {{ parent() }}
                                {{ form_errors(form) }}
                            {% endblock %}

                            {% include 'AppBundle:Backend/Cotacoes:form.html.twig' with {'form': form} %}

                            <div class="box-footer">
                                <button type="submit" class="btn btn-success">Salvar</button>
                                <a href="{{ path('backend_cotacoes_index') }}" class="btn btn-default">Voltar</a>
                            </div>

                        </form>

                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts filter='?uglifyjs2'
        '@AppBundle/Resources/public/js/custom/Agent/form.js'
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}